Repository liquality/cryptoassets, pull requests merged in 2022-05, with the labels that each got.

#82 feat: getSendGasLimitERC20
  src/assets/index.ts
  src/assets/native.ts
  src/assets/sendGasLimits.ts
  src/chains.ts
  src/index.ts
  src/types.ts
Labels: 🔍 Ready for Review, size/L

#86 feat: Add arbitrum tokens
  src/assets/erc20/arbitrum-tokens.json
  src/assets/erc20/index.ts
Labels: 🔍 Ready for Review, 🌟 Needs more Approvals, size/M

#89 Fix/hex validation
  src/common.ts
  tests/chains/avalanche.test.ts
Labels: size/XS, 🔍 Ready for Review
